version: "3"

# Project Name not allowed
# project_name: encointer-explorer
# use: docker-compose -p encointer-explorer up -d

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: postgres
    shm_size: 1gb
    ports:
      - "${DB_PORT}:5432"
      # command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
